In [1]:
import numpy as np

By default, `meshgrid(x, y)` uses `indexing='xy'`, meaning:

The first output (X) varies in the `column` direction.
The second output (Y) varies in the `row` direction.

'xy' is Matplotlib-style indexing.
- The first array output (X) has shape (len(y),len(x)). y rows, x columns
- The second array output (Y) also has shape (len(y),len(x)).
- Think: “X in the columns, Y in the rows.”


Intuitively: We are creating cartesian coordinates with `xy` indexing. The first element is an `x` coordinate and the second is `y`. 

In [2]:
x = [1, 2, 3]
y = [10, 11]

X, Y = np.meshgrid(x, y, indexing='xy')

print(X)
print(Y)

print(np.dstack((X, Y)))

[[1 2 3]
 [1 2 3]]
[[10 10 10]
 [11 11 11]]
[[[ 1 10]
  [ 2 10]
  [ 3 10]]

 [[ 1 11]
  [ 2 11]
  [ 3 11]]]


`ij` indexing is useful when you are looking to perform array like operations with a grid of numbers. Notice how each pairwise element can represent array accesses into a matrix (row first, then column.)

Suppose you do a loop for i in range(3): for j in range(2): ... which indexing scheme lines up directly with (i, j) from the loop?


In [3]:
rows = [0, 1, 2, 3]
cols = [4, 5, 6]

R, C = np.meshgrid(rows, cols, indexing = 'ij')
print(R)
print(C)

print(np.dstack((R, C)))

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
[[4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]]
[[[0 4]
  [0 5]
  [0 6]]

 [[1 4]
  [1 5]
  [1 6]]

 [[2 4]
  [2 5]
  [2 6]]

 [[3 4]
  [3 5]
  [3 6]]]


Q: Why does meshgrid return two separate arguments as opposed to a single combined grid?

meshgrid returns separate coordinate arrays (e.g., X and Y) instead of a single combined grid because most operations and plotting functions expect each dimension’s coordinates to be stored separately. This makes it easier to do element-wise calculations like f(X, Y) or to feed X, Y, Z arrays into contour/surface plots. If meshgrid returned a single array of shape (rows, cols, 2), you’d frequently have to split it back into separate X and Y components anyway.

It’s largely a design convention that emerged because it’s far more direct to handle 
X
X and 
Y
Y as separate 2D arrays than a single array of coordinate pairs. Here’s why:

Element-Wise Math:
If you want to evaluate f(x,y) at every grid point, separate arrays Y let you do Z = f(X, Y) directly, leveraging NumPy’s vectorized operations. If you had a single array of shape (rows, cols, 2), you’d have to slice or index out the x- and y-components first.

Plotting APIs:
Libraries like Matplotlib (and earlier MATLAB) designed their 2D plotting functions (contour, surface, etc.) to take matching arrays for each dimension and the function values. This “X, Y, Z must be the same shape” approach became the de facto standard.

Historical & Interoperability:
This convention dates back to older numeric environments (e.g., MATLAB), and NumPy/Matplotlib inherited it for compatibility and user familiarity. Many engineers and scientists already use separate coordinate arrays to specify domain and function values in academic papers, algorithms, etc.

Thus, returning two (or more) coordinate arrays is simply the most straightforward way to feed data into standard plotting and numeric libraries, while also being convenient for element-wise arithmetic in NumPy.


## 3D meshgrid

### Historical / Plotting Convention

- In a 2D scenario, 'xy' indexing is standard for contour or surface plotting (e.g., plt.contour(X, Y, Z)).
- The resulting arrays for X and Y with 'xy' indexing end up having shapes (Ny,Nx).
- This matches the way images are typically stored in row-major order:
Dimension 0 = “row” = y direction,
Dimension 1 = “column” = x direction.

Q: Why Flip x and y?
- In 2D images: The first dimension is the vertical axis (number of rows), and the second dimension is the horizontal axis (number of columns).
Plotting libraries like Matplotlib treat the first array dimension as “down the page” (the y-axis) and the second array dimension as “across the page” (the x-axis).

### Extending to 3D
When you give np.meshgrid(x, y, z, indexing='xy'):

- The first dimension remains the “y dimension” (length = len(y)).
- The second dimension is the “x dimension” (length = len(x)).
- The third dimension tacks on z (length = len(z)).
Thus the shape is (Ny,Nx,Nz). It’s just the 2D shape (Ny,Nx) with an additional z dimension appended last.

In [1]:
t = [0, 1]
x = [1, 2, 3]
y = [4, 5, 6, 7]

X, Y, T = np.meshgrid(x, y, t)

print("shape: %v", T.shape)
print("T: %v", T)
print("X: %v", X)
print("Y: %v", Y)

NameError: name 'np' is not defined

In [5]:
T, X, Y = np.meshgrid(t, x, y, indexing='ij')

print("shape: %v", T.shape)
print("T: %v", T)
print("X: %v", X)
print("Y: %v", Y)

shape: %v (2, 3, 4)
T: %v [[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
X: %v [[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]]
Y: %v [[[4 5 6 7]
  [4 5 6 7]
  [4 5 6 7]]

 [[4 5 6 7]
  [4 5 6 7]
  [4 5 6 7]]]


## Plotting